### Registrar usuario
POST http://localhost:5217/api/Auth/register
Content-Type: application/json

{
  "username": "maria",
  "email": "maria@correo.com",
  "password": "123456789"
}

### Login
POST http://localhost:5217/api/Auth/login
Content-Type: application/json

{
  "username": "maria",
  "password": "123456789"
}

### Crear Proyecto (pega aquí el token devuelto en el login)
POST http://localhost:5217/api/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibWFyaWEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiUGxhbiI6IkZyZWUiLCJleHAiOjE3ODI2OTE4MDIsImlzcyI6IlRhc2tFYXN5QVBJIiwiYXVkIjoiVGFza0Vhc3lVc3VhcmlvcyJ9.O9LN_MnurwbWiH5tEL8_61I0E9GAl6BzBQIs8dSKiyw

{
  "nombre": "Mi cuarto Proyecto",
  "descripcion": "Este es mi cuarto proyecto en TaskEasy"
}

### Crear Tarea en un proyecto
POST http://localhost:5217/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibWFyaWEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiUGxhbiI6IkZyZWUiLCJleHAiOjE3ODI2OTE4MDIsImlzcyI6IlRhc2tFYXN5QVBJIiwiYXVkIjoiVGFza0Vhc3lVc3VhcmlvcyJ9.O9LN_MnurwbWiH5tEL8_61I0E9GAl6BzBQIs8dSKiyw

{
  "titulo": "Primera tarea",
  "descripcion": "Tarea creada desde requests.http",
  "estado": "Pendiente",
  "fechaLimite": "2026-12-31T00:00:00",
  "projectId": 1
}

### Ver tareas de un proyecto
GET http://localhost:5217/api/tasks/project/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibWFyaWEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiUGxhbiI6IkZyZWUiLCJleHAiOjE3ODI2OTE4MDIsImlzcyI6IlRhc2tFYXN5QVBJIiwiYXVkIjoiVGFza0Vhc3lVc3VhcmlvcyJ9.O9LN_MnurwbWiH5tEL8_61I0E9GAl6BzBQIs8dSKiyw
